---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foobar
  labels:
    app: foobar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foobar
  template:
    metadata:
      name: foobar
      labels:
        app: foobar
    spec:
      containers:
        - name: foobar22222
          image: ghcr.io/tibeer/skopeo_worker:latest
          imagePullPolicy: Always
